global:
  scrape_interval: 30s
  evaluation_interval: 25s

scrape_configs:
  - job_name: 'api_health_monitor'
    static_configs:
      - targets: ['localhost:3002']

  - job_name: 'metrics'
    static_configs:
      - targets: ['localhost:3002']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      -targets: ['cadvisor:8080']