global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['52.62.131.103:8080']
      
  - job_name: 'gold-api'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['52.62.131.103:6002'] 

  - job_name: 'currency-api'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['52.62.131.103:6001'] 
      
  - job_name: "node_exporter"
    static_configs:
      - targets: ["52.62.131.103:9100"]
rule_files:
  - alert_rules.yml