global:
  scrape_interval: 10s

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'alertmanager:9093' ]

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
      
  - job_name: 'gold-api'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['gold-api:3002'] 

  - job_name: 'currency-api'
    metrics_path: '/metrics' 
    static_configs:
      - targets: ['currency-api:3002'] 
      
  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
      
rule_files:
  - alert_rules.yml
