version: '3.8'

services: 
  gold-api:
    container_name: gold-api
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6001:3002"  
    environment:
      - API_TYPE=gold  
    restart: 'on-failure'
    volumes:
      - .\index.js:/app/index.js

  currency-api: 
    container_name: currency-apis
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "6002:3002"  
    environment:
      - API_TYPE=currency 
    restart: 'on-failure'
    volumes:
      - .\index.js:/app/index.js

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'