route:
  receiver: 'Mail Alert'
  # group_by: [ alertname ]
  repeat_interval: 3m
  group_wait: 15s
  group_interval: 15s

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'smtp.gmail.com:587'
        auth_username: 'chunghoangminh2003@gmail.com'
        auth_password: "qngq bmzf ourz qbpc"
        from: 'chunghoangminh2003@gmail.com'
        to: 'lephankhoa2003nb2@gmail.com'
        headers:
          subject: 'Prometheus Mail Alerts'